# name: BuildScanPushDockerImage

# on:
  
#   workflow_dispatch:
#     inputs:
#       DockerPath:
#         description: 'Provide the Docker Pathj Relative to Git'
#         required: true
#         default: '/dockerfile'


# jobs:
  
#   BuildScanPush:
    
#     runs-on: ubuntu-latest

#     steps:
#       - name: extract branch name on push event
#         if: github.event_name != 'pull_request'
#         shell: bash
#         run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV; echo "HASH=${GITHUB_SHA::6}" >> $GITHUB_ENV; uname -m

#       - name: extract branch name on PR event
#         if: github.event_name == 'pull_request'
#         shell: bash
#         run: echo "BRANCH=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV; echo "HASH=${GITHUB_SHA::6}" >> $GITHUB_ENV;

#       - name: Get branch name
#         run: echo 'The branch name is' ${{ env.BRANCH }}; echo 'HASH is' ${{ env.HASH }}
      
#       - uses: actions/checkout@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@master
#         with:
#           platforms: all
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - run: |
#           docker build ${{ github.workspace }}/${{ github.event.inputs.DockerPath }}/ -t ${{ secrets.DOCKERHUB_USERNAME }}/cision:${{ env.BRANCH }}-${{ env.HASH }}
     
#       - name: Run Trivy vulnerability scanner
#         uses: aquasecurity/trivy-action@master
#         continue-on-error: false
#         with:
#          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/cision:${{ env.BRANCH }}-${{ env.HASH }}
#          format: 'sarif'
#          output: 'trivy-results.sarif'
         
#       - name: Upload Trivy scan results to GitHub Security tab
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#          sarif_file: 'trivy-results.sarif'
         
#       - run: |
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/cision:${{ env.BRANCH }}-${{ env.HASH }}
